name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Inject GOOGLE_API_KEY into index.html
      run: |
        sed -i 's/window.GOOGLE_API_KEY = '\''\'';/window.GOOGLE_API_KEY = "${{ secrets.GOOGLE_API_KEY }}";/' index.html

    - name: Build project
      run: npm run build

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: pl-hotelgarden
